# Hardened values for headlamp v0.24.0
# This file contains security-focused configurations for production deployment

# Security contexts
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

# Node scheduling
nodeSelector:
  kubernetes.io/os: linux

# Resource management
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# High availability
replicaCount: 2

# Service account configuration
serviceAccount:
  create: true
  automount: true  # Required for Kubernetes API access

# OIDC Authentication Configuration
# Using external secret approach for security
config:
  oidc:
    # Use external secret for OIDC credentials
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc-config
    # Additional OIDC settings
    scopes: "openid,profile,email,groups"
    useAccessToken: false  # Use ID token for better security

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration for OIDC callback
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # OIDC-specific security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'";
  hosts:
    - host: headlamp.example.com  # Replace with your actual domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.example.com

# Environment variables for OIDC
env:
  - name: HEADLAMP_OIDC_ENABLE
    value: "true"

# Network policies for security
networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 4466
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS to OIDC provider
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow Kubernetes API access
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: TCP
          port: 443

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Additional security configurations
podSecurityContext:
  fsGroup: 65534
  runAsGroup: 65534
  runAsUser: 65534
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Affinity for better distribution
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - headlamp
          topologyKey: kubernetes.io/hostname
