---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "namespace.yaml"
  - "source.yaml"
  - "helmrelease.yaml"
secretGenerator:
  - name: headlamp-values-base
    type: Opaque
    files:
      - hardened.yaml=helm-values/hardened-values-0.35.0.yaml
    options:
      disableNameSuffixHash: true
